# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    env:
      Configuration: Release

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # setup MSBuild
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet.exe
      uses: nuget/setup-nuget@v1
    
    # Runs a multiple command using the runners shell
    - name: Restore Nuget
      run: Nuget restore gxcli.sln

    # Runs a multiple command using the runners shell
    - name: Build Solution
      run: msbuild gxcli.sln /p:Configuration=${env:Configuration}

    - name: Set the version environment variable
      run: |
        $file = ".\src\gxcli\bin\${env:Configuration}\gx.exe"
        $env:GXCLI_VERSION = $(Get-Item $file).VersionInfo.ProductVersion
        Write-Host GXCLI_VERSION $env:GXCLI_VERSION
        echo "::set-env name=GXCLI_VERSION::$env:GXCLI_VERSION"

    - name: Deploy 
      run: .\deploy.ps1 .\deploy\ ${env:Configuration} $true
      shell: powershell

    - name: Zip it! 
      run: Compress-Archive .\deploy\* gxcli.zip
      shell: powershell

    - name: Create a Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ env.GXCLI_VERSION }}
        release_name: Release ${{ env.GXCLI_VERSION }}

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./gxcli.zip
        asset_name: gxcli.zip
        asset_content_type: application/zip